name: Build APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y python3-pip git zip unzip openjdk-17-jdk

      - name: Install Buildozer
        run: pip install buildozer

      - name: Init Buildozer
        run: |
          buildozer init
          sed -i 's/title = .*/title = May Day App/' buildozer.spec
          sed -i 's/package.name = .*/package.name = maydayapp/' buildozer.spec
          sed -i 's/package.domain = .*/package.domain = org.test/' buildozer.spec
          sed -i 's/requirements = .*/requirements = python3,pygame/' buildozer.spec

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: bin/*.apk
