name: Build APK

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip git zip unzip openjdk-17-jdk build-essential

      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: Install Buildozer and Cython
        run: |
          pip install buildozer cython

      - name: Init Buildozer
        run: |
          buildozer init

          sed -i 's/title = .*/title = First May/' buildozer.spec
          sed -i 's/package.name = .*/package.name = firstmay/' buildozer.spec
          sed -i 's/package.domain = .*/package.domain = org.test/' buildozer.spec

          sed -i 's/requirements = .*/requirements = python3,pygame/' buildozer.spec

          sed -i 's/# (str) Orientation/screen.orientation = portrait/' buildozer.spec

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
